export const categories = [
  {
    id: 1,
    name: "Fast Food",
    image: require("../assets/images/categories/icons8-hamburger-96.png"),
  },
  { 
    id: 2,
    name: "Noodles",
    image: require("../assets/images/categories/icons8-takeout-box-96.png"),
  },
    {
      id: 3,
      name: "Sweets",
      image: require("../assets/images/categories/sweets.png"),
    },
    {
      id: 4,
      name: "Sea Food",
      image: require("../assets/images/categories/chinese.png"),
    },
    {
      id: 5,
      name: "All",
      image: require("../assets/images/categories/icons8-pizza-96.png"),
    },
    {
      id: 6,
      name: "Italian",
      image: require("../assets/images/categories/icons8-spaghetti-96.png"),
    },
    
    
    
  ];
  
  export const featured = {
    id: 1,
    title: "Hot and Spicy",
    description: "local fast food corner",  
    restaurants: [
      {
        id: 1,
        name: "Papa Johns",
        image: require("../assets/images/restaurants/hero.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "Chicken Wings",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          { 
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/patates.jpeg"),
          },
        ],
      },
      {
        id: 2,
        name: "Green Salads",
        image: require("../assets/images/restaurants/salada.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chickenn.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
        ],
      },
      {
        id: 3,
        name: "Burger King",
        image: require("../assets/images/restaurants/burger.webp"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/patates.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/hamur.jpeg"),
          },
        ],
      },
      {
        id: 4,
        name: "Chinese & Sushi Express",
        image: require("../assets/images/restaurants/hero.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chickenn.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
        ],
      },
    ],
  };

  export const featuredd = {
    id: 1,
    title: "Fried Chicken",
    description: "soft and tender fried chicken",  
    restaurants: [
      {
        id: 1,
        name: "Burger King",
        image: require("../assets/images/restaurants/burger.webp"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/patates.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/hamur.jpeg"),
          },
        ],
      },
      {
        id: 2,
        name: "Papa Johns",
        image: require("../assets/images/restaurants/hero.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "Chicken Wings",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          { 
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/patates.jpeg"),
          },
        ],
      },
      {
        id: 3,
        name: "Green Salads",
        image: require("../assets/images/restaurants/salada.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chickenn.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
        ],
      },
      
      {
        id: 4,
        name: "Chinese & Sushi Express",
        image: require("../assets/images/restaurants/hero.jpg"),
        description: "Hot and spicy pizzas",
        lat: 38.2145602,
        lng: -85.5324269,
        address: "432 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Margherita Pizza",
            description: "Classic pizza with fresh mozzarella and basil.",
            price: 12,
            image: require("../assets/images/dishes/margaritaa.jpeg"),
          },
          {
            id: 2,
            name: "BBQ Chicken Pizza",
            description: "BBQ sauce, grilled chicken, and red onions.",
            price: 14,
            image: require("../assets/images/dishes/chickenn.jpeg"),
          },
          {
            id: 3,
            name: "Cheeseburger",
            description: "Juicy beef burger with lettuce, tomato, and cheese.",
            price: 10,
            image: require("../assets/images/dishes/cheeseburger.jpeg"),
          },
          {
            id: 4,
            name: "Caesar Salad",
            description: "Romaine lettuce, croutons, and Caesar dressing.",
            price: 8,
            image: require("../assets/images/dishes/sezar.jpeg"),
          },
          {
            id: 5,
            name: "Pasta Primavera",
            description: "Pasta with seasonal vegetables and olive oil.",
            price: 11,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
          {
            id: 6,
            name: "Shrimp Scampi",
            description: "Sautéed shrimp with garlic and lemon over pasta.",
            price: 16,
            image: require("../assets/images/dishes/shrim.jpeg"),
          },
          {
            id: 7,
            name: "Tacos",
            description: "Soft tacos with beef, lettuce, and salsa.",
            price: 9,
            image: require("../assets/images/dishes/tacos.jpeg"),
          },
          {
            id: 8,
            name: "Sushi Platter",
            description: "An assortment of fresh sushi rolls.",
            price: 18,
            image: require("../assets/images/dishes/sushi.jpeg"),
          },
          {
            id: 9,
            name: "Chocolate Cake",
            description: "Rich chocolate cake with ganache frosting.",
            price: 6,
            image: require("../assets/images/dishes/pasta.jpeg"),
          },
        ],
      },
    ],
  }; 